### ISSUE TITLE
Support --no-color option

### ISSUE THREAD

**Issue by tpetchel** [inspec/kitchen-inspec#103]
When I run `kitchen verify --no-color`, kitchen-inspec adds colorization markers to the output. I would expect kitchen-inspec to respect the `--no-color` flag.

```
...
       Compiling Cookbooks...
       Converging 0 resources

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/0 resources updated in 03 seconds
       Finished converging <default-centos-72> (0m33.53s).
-----> Setting up <default-centos-72>...
       Finished setting up <default-centos-72> (0m0.00s).
-----> Verifying <default-centos-72>...
       Use `/root/learn-chef/cookbooks/webserver_test/test/recipes/default` for testing

Target:  ssh://vagrant@127.0.0.1:2222

[31m  ✖  System Package httpd should be installedexpected that `System Package httpd` is installed[0m

Summary: [32m0 successful[0m, [31m1 failures[0m, [37m0 skipped[0m
```

```
$ chef --version
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2
```

```
$ chef gem list | grep kitchen-inspec
kitchen-inspec (0.15.0)
```

**Comment by vjeffrey** [comment]
looks like this issue traces all the way back to inspec.  running `inspec exec https://github.com/dev-sec/tests-ssh-hardening.git --no-color` provides colorized output: https://github.com/chef/inspec/issues/1024

**Comment by rjhornsby** [comment]
The flag is being honored (which is awesome, thanks!) as of a recent release included in chefdk, but not quite 100%. Errors are still being printed in red, ignoring the `--no-color` flag:

<img width="400" alt="screenshot 2017-02-25 17 04 17" src="https://cloud.githubusercontent.com/assets/5077610/23335559/2f7e0eec-fb7d-11e6-8863-44b2dd577c3b.png">

For reference, I'm using chefdk 1.2.22, which is kitchen 1.15.0 and kitchen-inspec 0.17.0.

**Comment by americanhanko** [comment]
+1 for this issue

```
$ chef --version
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21
```

![screenshot 2018-03-12 13 50 14](https://user-images.githubusercontent.com/8458267/37309962-c0e09532-25ff-11e8-9655-982160d6f14e.png)

**Comment by atward** [comment]
For anyone looking for a workaround: use `color` config option in kitchen.yml

```
verifier:
  name: inspec
  color: <%= !ENV.include?('CI') %>
```

**Comment by Vasu1105** [comment]
This issue needs to be fixed n test-kitchen and not the kitchen-inspec as kitchen verify command is handled at the side of test-kitchen. For kitchen-inspec user can use the `color: false` in the kitchen config file.

Also --no-color option works for the UI but not for the results . Just additional point

<img width="1536" alt="Screenshot 2021-06-01 at 12 27 38 PM" src="https://user-images.githubusercontent.com/4181545/120281002-0e155100-c2d6-11eb-9d2a-ac38eedb4dd1.png">

<img width="1536" alt="Screenshot 2021-06-01 at 12 26 18 PM" src="https://user-images.githubusercontent.com/4181545/120280929-f342dc80-c2d5-11eb-8f56-6baea01c9327.png">
