### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT while crawling a page which contains UTF Characters.

### ISSUE THREAD

**Issue by starx** [inspec/kitchen-inspec#146]
### Description

In a test, trying to verify contents of a web address by crawling is failing. 

>  ------Exception-------
>  Class: Kitchen::ActionFailed
>  Message: 1 actions failed.
>      Failed to complete #verify action: [incompatible character encodings: UTF-8 and ASCII-8BIT] on default-ubuntu-1604
> 

[Kitchen Log](https://pastebin.com/k36mGEY7)

### InSpec and Platform Version

Inspec: 1.31.1
Kitchen: 1.16.0

### Replication Case

A simple test case like this is enough. The page it is crawling should have Unicode characters. e.g. http://blog.mrnepal.com

```
describe command 'curl http://test.com' do
  its('stdout') { should match(/test_match/) }
end
```
I opened this [issue](https://github.com/chef/inspec/issues/2044) previously in chef/inspec was instructed that issue was not related to Inspec but this repo instead.

**Comment by pratik705** [comment]
Hi, 
I am hitting the exact issue on my test setup. any workaround/solution for the issue?

**Comment by lindhor** [comment]
Same for me in 1.43.5 and 2.2.27.

**Comment by lehn-etracker** [comment]
@pratik705 you can force `message` to be converted into UTF-8 by changing your local inspec reporter. Add `.force_encoding(Encoding::UTF_8)` within `format_message` method call like this:

`lib/inspec/reporters/cli.rb`:
```ruby
format_message(
         color: impact,
         indicator: impact,
         indentation: 5,
         message: message.force_encoding(Encoding::UTF_8),
)
```

Btw: you will find the full path to `cli.rb` within trace message from your inspec call.

**Comment by greeneg** [comment]
I can confirm that @lehn-etracker 's fix resolves this when doing a kitchen verify on older Linux versions that use non-UTF8 encodings.

**Comment by chris-rock** [comment]
Thank you @starx for reporting the issue. I added a PR in InSpec to add a functional test to verify that this does not happen again. Once merged you need to update to latest inspec to prevent the issue happening.

**Comment by starx** [comment]
@chris-rock That is Great news.
