### ISSUE TITLE
It's not possible to skip_controls in .kitchen.yml

### ISSUE THREAD

**Issue by aalmenar** [inspec/kitchen-inspec#156]
I have read all the docs on inspect and kitchen-inspec but i don't see any way possible to use it with the option skip_control, like its available on inspec profiles.

i don't know if it should be a feature to add to kitchen-inspec or use another profile with the skip_control.

Regards.

**Comment by walterdolce** [comment]
`skip_controls` would be a great addition. Or a great missing feature fix. It depends on how you look at it. 

;-P

**Comment by kekaichinose** [comment]
@walterdolce great ask! Keep an eye out on our upcoming waiver functionality as we'll look to incorporate this functionality into there. We'll be looking at getting that integrated in the next couple quarters. I'll close this issue out and capture this in the epic we cut for that work.

Thanks!
