### ISSUE TITLE
feature request: support outputting multiple reporter formats

### ISSUE THREAD

**Issue by ryancurrah** [inspec/kitchen-inspec#177]
In our CI tool we would like to have the `cli` output and `junit` report formats at the sametime. I'm not entirely sure this is possible in `kitchen-inspec` yet because `inspec` `2.0` just dropped. Is this possible yet?

**Comment by qvallance** [comment]
I saw that support for inspec 2.0 was added, but it looks like kitchen-inspec still expects the use of `format`, rather then the new `reporter` syntax, which allows specifying multiple output formats.
