### ISSUE TITLE
Expose "backend" InSpec configuration option

### ISSUE THREAD

**Issue by walterdolce** [inspec/kitchen-inspec#194]
Hi, 
While trying to directly use `kitchen-inspec` as a verifier over the one being used by `kitchen-terraform` instead, I found myself needing to provide the `backend` option to InSpec but this is not currently exposed and so it can't be passed in the `.kitchen.yml` file.

A quick search in GitHub and in the code shows the `backend_cache` option is exposed, though:
https://github.com/inspec/kitchen-inspec/search?q=backend&unscoped_q=backend

Am I right in assuming this config opton is currently not exposed because nobody asked for it and/or had a use case before now? :)

Thank you.

**Comment by clintoncwolfe** [comment]
I beleive this can be closed, as the underlying need on the kitchen-terraform project was addressed differently - see https://github.com/newcontext-oss/kitchen-terraform/issues/252#issuecomment-406801408
