### ISSUE TITLE
Upload inspec profile error.

### ISSUE THREAD

**Issue by rsluzhynskyy** [inspec/kitchen-inspec#223]
Even when I am trying to upload community inspec profile with latest inspec-3.6.12 I am getting an error:

-bash-4.2$ inspec compliance upload cis-windows2016rtm-level1-memberserver --overwrite
Dependencies for profile cis-windows2016rtm-level1-memberserver successfully vendored to /var/lib/jenkins/workspace/InspecCASync-vik2/cis-windows2016rtm-level1-memberserver/vendor
/var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-3.6.12/lib/inspec/backend.rb:45:in `create': undefined method `unpack_train_credentials' for {:target=>"mock://"}:Hash (NoMethodError)
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-3.6.12/lib/plugins/inspec-compliance/lib/inspec-compliance/cli.rb:144:in `upload'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/inspec-3.6.12/bin/inspec:12:in `<top (required)>'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/bin/inspec:22:in `load'
	from /var/lib/jenkins/.rbenv/versions/2.4.1/bin/inspec:22:in `<main>'

**Comment by clintoncwolfe** [comment]
This repository handles issues related to the test-kitchen plugin, `kitchen-inspec`. Please open an issue on https://github.com/inspec/inspec .
