### ISSUE TITLE
Add license gating to kitchen-inspec

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/kitchen-inspec#227]
### Describe the Enhancement:
Accept chef license when running InSpec via kitchen-inspec from Chef workstation.  If running kitchen-inspec without a workstation install, apparently this is intended to run without license gating.

This is a major version change.

### Describe the Need:
All InSpec 4+ users

**Comment by aaronlippold** [comment]
given that 4.0.8 does not allow for an escape hatch, should we prioritize this so we are not breaking kitchen ci/cd builds

**Comment by clintoncwolfe** [comment]
4.0.8 is not a full release; we should talk about 4.3.2 and later.

Here is the plan:
 1. If you are calling Inspec::Runner yourself directly from your Ruby code, you are "using InSpec as a library" and are not subject to the license.
 2. If you use kitchen-inspec (which calls Inspec::Runner) from your custom gem install, my current understanding is that this is also a non-licensed use. I may be wrong here.
 3. If you use kicthen-inspec from a ChefDK or Chef Workstation installation, you will need to accept the license

So, we'll be adding code to kitchen-inspec to detect case 3 and prompt for license acceptance.  Make sense?

**Comment by tas50** [comment]
#2 is correct based on our past conversations with product

**Comment by tas50** [comment]
Closing this out based on the library usage of inspec here.
