### ISSUE TITLE
Passing variable to inspec.yml

### ISSUE THREAD

**Issue by DhaneshRaghavan-alation** [inspec/kitchen-inspec#228]
I would like to pass the different includes(platform name such as debian, ubuntu) to the inspec.yml file attribute "name" to get the name of platform in the attribute test_suite in xml output. Is there any way to pass the platform name to the inspec.yml file inside the inspec profile.

**Comment by clintoncwolfe** [comment]
followup: confusing kitchen `platform` option set with inspec platform detection
