### ISSUE TITLE
Verifier Inspec does not support the Rsync Transport

### ISSUE THREAD

**Issue by Gary-Armstrong** [inspec/kitchen-inspec#232]
# Version:

Chef Workstation: 0.2.53
  chef-run: 0.2.8
  chef-client: 14.10.9
  delivery-cli: 0.0.52 (9d07501a3b347cc687c902319d23dc32dd5fa621)
  berks: 7.0.7
  test-kitchen: 1.24.0
  inspec: 3.6.6

# Environment:

macos, rbenv "chef-workstation"

# Scenario:

kitchen test <name>

# Steps to Reproduce:

Dust off old cookbook, run kitchen test <cb.name>

# Expected Result:

Kitchen tests

# Actual Result:

-----> Verifying <compute-centos69-1805-m3medium>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Verifier Inspec does not support the Rsync Transport] on compute-centos69-1805-m3medium
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by zenspider** [comment]
Correct. rsync is not supported at this time. Closing.
