### ISSUE TITLE
Add support for ENV['TEST_KITCHEN'] and ENV['CI']

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/kitchen-inspec#233]
### Describe the Enhancement:

Being able to use `only_if { !ENV['TEST_KITCHEN'] }` inside of InSpec controls.

### Describe the Need:

In `kitchen converge` I can skip certain things by using `ENV['TEST_KITCHEN']`. For example, let's say I have a recipe that renames the local Administrator on Windows (very common "hardening" task"). I can skip this in converge, but I cannot skip the test for it in verify.

### Current Alternative

1. Convert default InSpec test to a profile and pass in an attribute.
2. Use a Lifecycle Hook to write a file and use `only_if` with `!file.exist()?`

### Can We Help You Implement This?:

Would love to help time permitting...but can't commit to it.

**Comment by jerryaldrichiii** [comment]
Closing this as I do not support Chef's contract with ICE and no longer care about the result of this ticket.

**Comment by mromero-convoso** [comment]
is there still no way to do this?
